steps:
  - commands:
      - ". $HOME/.asdf/asdf.sh"
      - "asdf local erlang 22.1.8"
      - "make compile"
      - "make ci"
    name: ":hammer: build"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"
