steps:
  - commands:
      - ". $HOME/.asdf/asdf.sh"
      - "asdf local erlang 22.1.8"
      - "make compile"
      - "make ci"
    name: ":hammer: build"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"

  - if: build.tag != null
    name: ":whale: docker"
    agents:
      queue: "erlang"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_arm64_docker.sh"
      - ".buildkite/scripts/make_arm32_docker.sh"



